name: alan
description: Pure Dart library to easily integrate with any Cosmos-based chain.
version: 0.41.2+1
homepage: https://github.com/alan-sdk/alan.dart
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ">=3.4.1 <5.0.0"
  asn1lib: ^1.0.0
  bech32: ^0.2.0
  bip39: ^1.0.6
  convert: ^3.0.0
  equatable: ^2.0.0
  fixnum: ^1.0.0
  grpc: ^3.0.0
  hex: ^0.2.0
  http: ^0.13.0
  json_annotation: ^4.4.0
  json_serializable: ^6.2.0
  meta: ^1.3.0
  pointycastle: ^3.0.1
  protobuf: ^2.0.0

dev_dependencies:
  build_runner: ^2.1.11
  mockito: ^5.0.3
  mock_web_server: ^5.0.0-nullsafety.1
  pedantic: ^1.11.0
  test: ^1.16.8
