name: sacco
description: Pure Dart library allowing you to easily create an HD Wallet and create, sign and send Cosmos-SDK transactions.
version: 0.0.14
author: Riccardo Montagnin <riccardo.montagnin@gmail.com>
homepage: https://github.com/commercionetwork/sacco.dart

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  meta: ^1.1.8
  hex: ^0.1.2
  http: ^0.12.0+2
  equatable: ^1.0.1

  # Crypto utils
  asn1lib: ^0.5.14
  bip32: ^1.0.5
  bip39: ^1.0.3
  bitcoin_flutter: ^1.0.7
  pointycastle: ^1.0.2
  bip_bech32: ^0.1.3

dev_dependencies:
  test: ^1.9.4
